### ISSUE TITLE
垃圾邮件可以不发送给博主吗？

### ISSUE THREAD

**Issue by inkss** [DesertsP/Valine-Admin#106]
如题，有个配置项开关也行。垃圾评论确实被过滤掉了，但是还是收到了邮件通知

**Comment by inkss** [comment]
`spam.checkSpam(currentComment, ip)`  似乎是个异步请求，请问如何修改为同步请求呢？

**Comment by inkss** [comment]
不知道怎么改掉这个异步请求，我只能用  setTimeout 等几十秒时间了

**Comment by Borber** [comment]
你好 这个问题解决了吗?

**Comment by inkss** [comment]
验证辣鸡评论的函数是个异步函数，在结果没出来之前，就到了发送博主邮件的代码。

所以改一下，等结果出来，我是这样改的：[查看链接](https://github.com/inkss/Valine-Admin/commit/5280de5a13a08579040e0cea199958b9b4a8df07)

**Comment by Borber** [comment]
> 验证辣鸡评论的函数是个异步函数，在结果没出来之前，就到了发送博主邮件的代码。
> 
> 所以改一下，等结果出来，我是这样改的：[查看链接](https://github.com/inkss/Valine-Admin/commit/5280de5a13a08579040e0cea199958b9b4a8df07)

我可以直接 使用你的代码部署吗?
