### ISSUE TITLE
Leancloud云引擎设置界面往哪里来的代码库？

### ISSUE THREAD

**Issue by suyin-long** [DesertsP/Valine-Admin#109]
步骤中说的在Leancloud云引擎设置界面，填充代码库并保存：https : //github.com/DesertsP/Valine-Admin.git
这里的代码库在哪？
![123](https://user-images.githubusercontent.com/49554285/87186970-fc723600-c31e-11ea-89fc-0d896ebbe36c.png)

已经部署的项目怎么删除？

**Comment by 799953468** [comment]
部署-Git部署

**Comment by suyin-long** [comment]
> 部署-Git部署

哪来的Git部署？
![QQ截图20200728002753](https://user-images.githubusercontent.com/49554285/88566893-440bf800-d069-11ea-9c9a-c24f1c80d47a.png)

**Comment by 799953468** [comment]
部署项目-git部署-配置git

**Comment by suyin-long** [comment]
> 部署项目-git部署-配置git

好的，谢谢！
