### ISSUE TITLE
更换邮件主题遇到问题

### ISSUE THREAD

**Issue by xuan-ming** [DesertsP/Valine-Admin#110]
我新建了环境变量把TEMPLATE_NAME的变量值填写为了rainbow，但是通知主题还是默认的。

**Comment by Spoience** [comment]
> 我新建了环境变量把TEMPLATE_NAME的变量值填充为彩虹，但是通知主题还是替换的。

更改了环境变量保存后重启下云引擎

**Comment by DesertsP** [comment]
> > 我新建了环境变量把TEMPLATE_NAME的变量值填充为彩虹，但是通知主题还是替换的。
> 
> 更改了环境变量保存后重启下云引擎

是的重启即可。
