### ISSUE TITLE
关于leancloud部署bug

### ISSUE THREAD

**Issue by zygds** [DesertsP/Valine-Admin#115]
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! Linux 4.15.0-99-generic
npm ERR! argv "/usr/local/nvm/versions/node/v6.17.1/bin/node" "/usr/local/bin/npm" "install" "--production"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code EREADFILE

npm ERR! Error extracting /home/leanengine/.npm/miniprogram-api-typings/2.10.4/package.tgz archive: ENOENT: no such file or directory, open '/home/leanengine/.npm/miniprogram-api-typings/2.10.4/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/leanengine/app/npm-debug.log

**Comment by DesertsP** [comment]
建议重新部署试试。
