### ISSUE TITLE
502错误，希望帮忙看下，谢谢

### ISSUE THREAD

**Issue by yesiare-cn** [DesertsP/Valine-Admin#118]
![图片](https://user-images.githubusercontent.com/69584990/90337623-43d29d00-e016-11ea-9159-8befbf16a7e6.png)

**Comment by yesiare-cn** [comment]
我直接截的图

**Comment by BillScott1024** [comment]
我也报了这个错有解决方案吗？

**Comment by BillScott1024** [comment]
(node:33) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by yesiare-cn** [comment]
> 
> 
> (node:33) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

解决了，我忘记加了一个环境变量

SENDER_EMAIL
