### ISSUE TITLE
(node:33) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

### ISSUE THREAD

**Issue by BillScott1024** [DesertsP/Valine-Admin#120]
(node:33) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

**Comment by mxy493** [comment]
遇到了同样的，不知道有没啥影响
`(node:31) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated`

**Comment by QingxuMo** [comment]
也碰到了这个问题
```
DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```

**Comment by Spoience** [comment]
我通过修改package.json中的node版本为：11.x 似乎可以解决nodejs 12.x不再支持这个的警告

**Comment by QingxuMo** [comment]
> 我通过修改package.json中的node版本为：11.x 似乎可以解决nodejs 12.x不再支持这个的警告

emmm，我觉得降级不是一个好的解决方法

**Comment by Spoience** [comment]
> > 我通过修改package.json中的node版本为：11.x 似乎可以解决nodejs 12.x不再支持这个的警告
> 
> emmm，我觉得降级不是一个好的解决方法

但是现在没这个警告了，评论试了下好像也没问题😂

**Comment by DesertsP** [comment]
> Node version 12 depracated OutgoingMessage.prototype._headers, which is used in http-server. Issue is listed at: https://github.com/http-party/http-server/issues/537
