### ISSUE TITLE
README pictures expired

### ISSUE THREAD

**Issue by yihuajack** [DesertsP/Valine-Admin#123]
As is shown below:
![2020-09-27_190451](https://user-images.githubusercontent.com/23608500/94363373-5ac7dd00-00f4-11eb-807e-049d851092ed.png)
The pictures in README do not show properly no matter using proxy or not while this problem not occurring in other GitHub sites. Probably the links of these pictures are invalid. Consider update them.

**Comment by yihuajack** [comment]
In addition, images "设置仓库" "环境变量" "二级域名" "一键部署" "部署过程" "唤醒云引擎" "mail-blue-template" "彩虹模板" "重启云引擎" now showing, but images "评论管理" and "创建定时器" can be shown correctly.

**Comment by DesertsP** [comment]
Thx. Readme updated now.
