### ISSUE TITLE
评论的后台管理系统无法登陆

### ISSUE THREAD

**Issue by youthlql** [DesertsP/Valine-Admin#125]
![image](https://user-images.githubusercontent.com/49017153/95159252-2e851e00-07d0-11eb-8c4c-9f960804bc95.png)
一直转圈

**Comment by DesertsP** [comment]
建议清空-User表，重新访问/sign-up页面填写管理员信息。
或者能否提供以下后台日志或者更多信息呢？我这边重新部署了一遍，没有出现问题。

**Comment by youthlql** [comment]
已解决多谢~
