### ISSUE TITLE
建议增加ip屏蔽功能

### ISSUE THREAD

**Issue by sxyugao** [DesertsP/Valine-Admin#24]
RT，最近很受垃圾评论困扰。。

但是自带的评论过滤插件不知道为什么没有屏蔽掉。。

![](https://i.loli.net/2019/02/21/5c6e4a3141d31.png)

**Comment by DesertsP** [comment]
Akismet是能够有效屏蔽垃圾评论的IP的。日志表明ValineAdmin获取到的是内网IP，原因是使用了其他版本的Valine评论框前端，获取正确的IP地址需要前端的配合，可以使用Deserts维护的Valine最新版，或者向相关作者发起功能请求。

（目前Leancloud云引擎无法获取访客的真实外网IP，未来也不会支持，因此VA对IP获取无能为力。）

**Comment by sxyugao** [comment]
谢谢您的指导

**Comment by DesertsP** [comment]
接下来的版本中，将加入『审核后发布』的功能，这对于不愿意用Akismet又厌恶垃圾评论的人来说或许有点用

**Comment by sxyugao** [comment]
您是不是应该更新一下您valine的安装链接。。

**Comment by DesertsP** [comment]
感谢你的反馈，链接已经更新。
评论人工审核后发表现已支持。
如果短期内垃圾评论实在猖狂，我的建议是启用人工审核，另外可以强制填写邮箱。
