### ISSUE TITLE
邮件提醒：多了一封<重设 hexo 的密码>

### ISSUE THREAD

**Issue by MikoyChinese** [DesertsP/Valine-Admin#27]
邮件提醒正常，但是每次会多一封：
您请求重设应用 hexo 的密码。点击下列链接来重设您的帐号密码（链接在 48 小时内有效）：

这是什么原因造成的？有人知道么？

**Comment by MikoyChinese** [comment]
我看了一下，是leancloud 内置的邮件模板，但问题是我没有启用它，它也会每次发一条给我？如何关闭它呢？

**Comment by DesertsP** [comment]
Valine前端参数notify：false，具体请查阅相关文档
