### ISSUE TITLE
启用人工审核后，还是立马展示留言。

### ISSUE THREAD

**Issue by guotao** [DesertsP/Valine-Admin#28]
预期应该是后台审核后才显示吧，可是目前是直接展示，只是后台标记为垃圾评论？
用的是 https://cdn.bootcss.com/valine/1.3.4/Valine.min.js 这个版本的Valine，貌似Valine也需要做一下处理。。。。

**Comment by DesertsP** [comment]
需要相应前端支持，可以使用我发布的Valine或者修改其他Valine的查询语句，isSpam字段为true的评论不予展示

**Comment by guotao** [comment]
OK
