### ISSUE TITLE
作者你好，你的项目Valine设置path参数无效

### ISSUE THREAD

**Issue by kangvcar** [DesertsP/Valine-Admin#33]
[https://github.com/DesertsP/Valine](https://github.com/DesertsP/Valine)
这个项目好像关闭了Issues，所以就来这里了，希望作者能看到，
我的站点[http://jike.freevar.com](http://jike.freevar.com)
我设置了`path: window.location.href` 希望每部影片有对应的评论，而不是所有影片的是相同评论。但是设置了该参数后并不生效。

 ps:在原版Valine设置`path: window.location.href`参数是生效的。

**Comment by DesertsP** [comment]
近期更新，谢谢反馈

**Comment by kangvcar** [comment]
@DesertsP 期待你的更新！

**Comment by kangvcar** [comment]
@DesertsP 请问作者是否已修复path: window.location.href参数无效的问题？

**Comment by DesertsP** [comment]
@kangvcar 我发现你这边在用旧版，这个问题应该很早之前就修复了

**Comment by kangvcar** [comment]
好的，谢谢
