### ISSUE TITLE
发不出去

### ISSUE THREAD

**Issue by LiYanan2004** [DesertsP/Valine-Admin#42]
![B24F9F36-84C3-4CAF-9FAF-05625A5C2B45](https://user-images.githubusercontent.com/37542129/56466627-9746d200-6446-11e9-93be-aa22a23fb0de.jpeg)

**Comment by DesertsP** [comment]
检查SMTP配置

**Comment by LiYanan2004** [comment]
哦哦我去看看

**Comment by LiYanan2004** [comment]
重启了三次云引擎，现在好了，开发者能做一个检查邮箱失败后自动重试的东西嘛，我觉得这个失败可能是云引擎的bug

**Comment by DesertsP** [comment]
> 重启了三次云引擎，现在好了，开发者能做一个检查邮箱失败后自动重试的东西嘛，我觉得这个失败可能是云引擎的bug

是邮箱运营商的限制，没办法

**Comment by LiYanan2004** [comment]
哪个邮箱运营商会好一点呢
