### ISSUE TITLE
关于垃圾评论的过滤

### ISSUE THREAD

**Issue by sxyugao** [DesertsP/Valine-Admin#43]
Akismet 貌似没有成功过滤掉垃圾评论，能直接默认局域网 ip 为垃圾评论吗。。

![](https://i.loli.net/2019/04/21/5cbc2159e2942.png)

**Comment by DesertsP** [comment]
用原版Valine 无法获取正确IP，可以开启人工审核模式

**Comment by sxyugao** [comment]
但是只有这几个垃圾评论是错误的，其他都是正确的？

**Comment by DesertsP** [comment]
明白你的情况了。这种垃圾评论是爬虫刷的ip一定是错的。如果被垃圾盯上了建议开启人工审核
