### ISSUE TITLE
定时任务的云函数命名不符合要求，无法保存

### ISSUE THREAD

**Issue by Magnetic2014** [DesertsP/Valine-Admin#46]
定时任务界面设置唤醒函数的时候，leancloud提示云函数名称只能包括字母数字下划线，无法保存。

可否把云函数名称中的"-"替换为"_"呢？

![image](https://user-images.githubusercontent.com/14221971/58221738-357bcf80-7d46-11e9-919c-d45759e846d5.png)

**Comment by DesertsP** [comment]
可以的，接下来修复。谢谢反馈！

**Comment by DesertsP** [comment]
已经更新云函数名称，请重新部署试试

**Comment by Magnetic2014** [comment]
OK，这回可以了，非常感谢
