### ISSUE TITLE
邮箱发送失败

### ISSUE THREAD

**Issue by mstao** [DesertsP/Valine-Admin#47]
![Snipaste_2019-06-01_21-48-42](https://user-images.githubusercontent.com/23411433/58749312-1ce28680-84b7-11e9-9b7f-5a9e28a2750c.png)

**Comment by mstao** [comment]
126  和qq 邮箱 都是这个错

**Comment by Chgtaxihe** [comment]
我也遇到了这个问题，设置一下环境变量`SMTP_HOST`就好了

**Comment by mstao** [comment]
不行啊，你怎么设置的，方便截个图吗？下面是我的。

![TIM图片20191018090430](https://user-images.githubusercontent.com/23411433/67058061-b4562680-f185-11e9-80e9-16d02c21125b.png)

**Comment by mstao** [comment]
好了，重启下实例
