### ISSUE TITLE
一个报错

### ISSUE THREAD

**Issue by Billraozihan** [DesertsP/Valine-Admin#54]
我在使用邮件发送的功能时报错535

**Comment by gogoio** [comment]
一般是邮箱密码错误，或者SMTP服务器配置错误。

**Comment by LG32** [comment]
如果你使用的是qq邮箱，可以试试在你的qq邮箱设置中开启POP3/SMTP服务，并将生成的码填入SMTP_PASS中。

**Comment by deserce** [comment]
使用163开启客户端授权密码[SMTP_PASS]

**Comment by DesertsP** [comment]
163、qq等邮箱，密码都不是账户密码，有SMTP授权码
