### ISSUE TITLE
国际版的评论后台不能注册 

### ISSUE THREAD

**Issue by OuYanghaoyue** [DesertsP/Valine-Admin#56]
国际版的评论后台不能注册 https://haoyue.avosapps.us/sign-up  打开显示not found
,但是 https://haoyue.avosapps.us/   可以正常打开，请问是怎么回事？？
如图
![TIM图片20190814104509](https://user-images.githubusercontent.com/39338698/62991040-b13a7380-be80-11e9-83f6-d81cddbe6229.png)

**Comment by BurgerTown** [comment]
删除_User里的所有数据
