### ISSUE TITLE
qq邮件发送失败Error501

### ISSUE THREAD

**Issue by mjx-dev** [DesertsP/Valine-Admin#57]
发送邮件提醒时会提示501 mail from address must be same as authorization user,发件失败,请帮忙看看
![image](https://user-images.githubusercontent.com/25698401/63662167-0adf5e00-c7f0-11e9-9216-2238e0cbd394.png)

**Comment by mjx-dev** [comment]
OK,解决了

**Comment by mjx-dev** [comment]
麻烦博主了

**Comment by LG32** [comment]
请问是怎样解决的，我也遇到了这个问题 @mjx-dev
