### ISSUE TITLE
there are two repeated comments shown评论重复出现

### ISSUE THREAD

**Issue by shj37** [DesertsP/Valine-Admin#72]
评论重复出现
Here is the website for reference https://eduunited.org/2019/12/21/testcomment/
I am using Hexo Hueman by the way.
Thank you.
![PVALA_OY$G)3(4H2{FAZ2$V](https://user-images.githubusercontent.com/8279674/71323600-ef6f3000-250f-11ea-8066-95a9627af96b.png)
解决了，请删掉

**Comment by yyl125** [comment]
@shj37 请问一下，是怎么解决的？
