### ISSUE TITLE
定时任务报错

### ISSUE THREAD

**Issue by WilliamPeterMatthew** [DesertsP/Valine-Admin#79]
![](https://s2.ax1x.com/2020/03/04/3oLx81.png)  
求教如何解决报错。

**Comment by DesertsP** [comment]
按照提示重新部署呢？

**Comment by imaegoo** [comment]
同样的问题+1

只有云引擎是运行状态，自唤醒才能成功，云引擎休眠状态，自唤醒总是失败。

我是从5月9日起开始遇到这个情况的。

**Comment by pic2debug** [comment]
> 同样的问题+1
> 
> 只有云引擎是运行状态，自唤醒才能成功，云引擎休眠状态，自唤醒总是失败。
> 
> 我是从5月9日起开始遇到这个情况的。

是leancloud官方的问题。详情请看这里https://forum.leancloud.cn/t/topic/22595  免费体验版对定时自唤醒做了限制，基本上100%失败。

**Comment by imaegoo** [comment]
> 是leancloud官方的问题。详情请看这里https://forum.leancloud.cn/t/topic/22595 免费体验版对定时自唤醒做了限制，基本上100%失败。

今天测试发现，即使将定时任务设置在非集中唤醒的时间（如每小时的26分26秒），也依旧收到400错误。

目前只能在别的云主机上写一个 crontab 去唤醒。

**Comment by sli1989** [comment]
大佬们有新的方法吗？流控问题。

**Comment by imaegoo** [comment]
@sli1989 
可参考 flexiston 的解决方法
https://www.flexiston.com/posts/25909.html

**Comment by hopeko** [comment]
@imaegoo 这个方法有效，但是想问一个问题，为什么这个唤醒是从8点到24点，而那个self_wake也是7点到24点，为什么都不设置24小时呢？是不是有什么雷区？

**Comment by imaegoo** [comment]
@hopeko https://leancloud.cn/docs/leanengine_plan.html#hash633315134

> 体验实例会执行休眠策略：
> * 强制休眠：如果最近 24 小时内累计运行超过 18 小时，则强制休眠。此时新的请求会收到 503 的错误响应码，该错误可在 云引擎 > 统计 中查看。
