### ISSUE TITLE
有的评论竟然不会发送邮件通知

### ISSUE THREAD

**Issue by redstoneleo** [DesertsP/Valine-Admin#80]
现在只有部分评论才会有通知，不知道怎么回事
![image](https://user-images.githubusercontent.com/5896180/76035900-9dba3b80-5f7d-11ea-98b2-13b590606e05.png)

**Comment by DesertsP** [comment]
没有留邮箱或者邮箱是假的。

**Comment by redstoneleo** [comment]
请问怎么设置强制必须填邮箱？
