### ISSUE TITLE
535error

### ISSUE THREAD

**Issue by MaskXman** [DesertsP/Valine-Admin#86]
Error: Invalid login: 535 Error: ÇëÊ¹ÓÃÊÚÈ¨ÂëµÇÂ¼¡£ÏêÇéÇë¿´: http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
这个问题该如何解决呀，邮箱设置了授权码，功能也都开起了

**Comment by DesertsP** [comment]
QQ邮箱的问题，可能是异地登陆保护
