### ISSUE TITLE
LeanCloud部署失败

### ISSUE THREAD

**Issue by wangtianya** [DesertsP/Valine-Admin#87]
部署失败：npm WARN deprecated ejs@2.3.1: Critical security bugs fixed in 2.5.5
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! Linux 4.15.0-66-generic
npm ERR! argv "/usr/local/nvm/versions/node/v6.17.1/bin/node" "/usr/local/bin/npm" "install" "--production" "--https-proxy=http://proxy.leancloud.cn:8080" "--proxy=http://proxy.leancloud.cn:8080"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code EREADFILE

npm ERR! Error extracting /home/leanengine/.npm/miniprogram-api-typings/2.10.2/package.tgz archive: ENOENT: no such file or directory, open '/home/leanengine/.npm/miniprogram-api-typings/2.10.2/package.tgz'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/leanengine/app/npm-debug.log

**Comment by wangtianya** [comment]
我去看看华东节点

**Comment by wangtianya** [comment]
确认，华北节点会失败，华东OK。

**Comment by weakish** [comment]
可以尝试下升级 node 版本（比如升级到 node 12

**Comment by Royce2019** [comment]
> 确认，华北节点会失败，华东OK。

我这华东失败，想问下怎么解决的

**Comment by Royce2019** [comment]
> 可以尝试下升级 node 版本（比如升级到 node 12

请问应该怎么升级

**Comment by Royce2019** [comment]
> 可以尝试下升级 node 版本（比如升级到 node 12

谢谢，已经解决

**Comment by Roc136** [comment]
请问不更换节点有解决办法吗

**Comment by Royce003** [comment]
> 请问不更换节点有解决办法吗

已经在 https://github.com/DesertsP/Valine-Admin/pull/89 中解决了，最新版应该不会出现这个问题了
如果是你自己的仓库，按 PR 的进行修改就行

**Comment by Roc136** [comment]
> > 请问不更换节点有解决办法吗
> 
> 已经在 #89 中解决了，最新版应该不会出现这个问题了
> 如果是你自己的仓库，按 PR 的进行修改就行

感谢！更换node版本至12.18.0可以解决问题~
