### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by constown** [DesertsP/Valine-Admin#90]
![image](https://user-images.githubusercontent.com/50108901/79036128-a7c3ff80-7bf7-11ea-99cd-7e324d528060.png)

部署失败。

**Comment by Royce2019** [comment]
https://github.com/DesertsP/Valine-Admin/pull/89
更新nodejs就行了

**Comment by constown** [comment]
把我电脑的node版本更新为这个指定版本吗？


我目前的node版本为13.8.0
npm 版本为 6.13.6




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Royce2019"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月11日(星期六) 中午1:45
收件人:&nbsp;"DesertsP/Valine-Admin"<Valine-Admin@noreply.github.com&gt;;
抄送:&nbsp;"卷二兔"<912300601@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DesertsP/Valine-Admin] 部署失败 (#90)





 
#89
 更新nodejs就行了

**Comment by Royce2019** [comment]
是更新leancloud上部署的源码中的，作者还没更新，可以先把仓库fork到自己那进行修改，参考https://github.com/DesertsP/Valine-Admin/pull/89，然后leancloud中换成自己的仓库

**Comment by constown** [comment]
十分感谢。已经成功部署!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Royce2019"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月11日(星期六) 中午1:50
收件人:&nbsp;"DesertsP/Valine-Admin"<Valine-Admin@noreply.github.com&gt;;
抄送:&nbsp;"卷二兔"<912300601@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [DesertsP/Valine-Admin] 部署失败 (#90)





 
是更新leancloud上部署的源码中的，作者还没更新，可以先把仓库fork到自己那进行修改，参考#89 ，然后leancloud中换成自己的仓库

**Comment by DesertsP** [comment]
> #89
> 更新nodejs就行了

感谢你的分享😋
