### ISSUE TITLE
大佬国际版没有布置代码库的选项

### ISSUE THREAD

**Issue by Cheny233** [DesertsP/Valine-Admin#96]
![C_4GIR$03E}LU9@UL~G8246](https://user-images.githubusercontent.com/49137980/80953656-8b019d00-8e2e-11ea-8fd6-a21bb2841b69.png)
如图，这是什么原因

**Comment by hfge** [comment]
![image](https://user-images.githubusercontent.com/34589275/80962502-bc369900-8e3f-11ea-8871-c3477c0b838e.png)
在这里。

**Comment by Cheny233** [comment]
感谢，找到了
